### ISSUE TITLE
The image on the Endorse this project section is broken

### ISSUE THREAD

**Issue by Ranhiru** [sleepyfox/coffeescript-koans#12]
The image link seems to be broken

**Comment by sleepyfox** [comment]
Thanks for bringing this to my attention. The underlying issue is with coderwall.com - not only have they changed their API from HTTP to HTTPS without talking to any of their customers (grrr) but they've also broken it. Normally I might fix it for them, but instead of it being an open github project it's been hidden behind a complex layer of 'assembly' which means you have to register and raise a bitcoin bounty and and and in order to get anything done, which seems way-overcomplicated for what should be a simple fix...
